/**
 * Copyright 2019 the orbs-client-sdk-javascript authors
 * This file is part of the orbs-client-sdk-javascript library in the Orbs project.
 *
 * This source code is licensed under the MIT license found in the LICENSE file in the root directory of this source tree.
 * The above notice should be included in all copies or substantial portions of the software.
 */

import * as Digest from "./Digest";
import { encodeHex } from "./Encoding";

test("HexEncodeWithChecksum", () => {
    expect(() => { Digest.contractNameToAddressAsBytes(""); }).toThrowError("invalid contract name");

    // This value was generated by orbs-contract-sdk-go which was tested with an e2e test against gamma
    expect(encodeHex(Digest.contractNameToAddressAsBytes("ERC721Receiver1567581564581813000"))).toEqual("0x63D2fE13c426Fe78E3C92E0B22d04508c54aA4BF");
});